---
- name: this is block in line file
  hosts: all
  tasks:
    - name: block in line
      block infile:
        path: /root/ .ssh/authorized_key
        block:
           this is the block
           it can span multiple lines
...             