---
- name: example playbook.yml
  hosts: all
  become: yes
  vars:
    package: httpd

  tasks:
    - name: installing package
      yum:
        name: "{{package}}"
        state: latest
