---
- name: example playbook.yml
  hosts: all
  become: yes
  vars:
    package: apache2

  tasks:
    - name: installing package
      apt:
        name: "{{package}}"
        state: latest
