---
- name: conditioner playbook example
  hosts: all
  tasks:
    - name: Check if process is running
      shell: ps -ef | grep sleep | grep -v grep
      ignore_errors: yes
      register: sleep_process_status

    - name: Debug message
      debug:
        msg: "Hello, world"
      