---
- name: conditioner playbook example
  hosts: all
  tasks:
    - name: Check if process is running
      shell: ps -ef | grep sleep | grep -v grep
      ignore_errors: yes
      

    - name: play any playbook
      debug:
        msg: "Hello, world"
      