---
- name: playbook one
  hosts: ubuntu
  become: true
  tasks:
    - name: line in file
    lineinfile:
      path: /home/ubuntu/.ssh/authorized_keys
      line: 'this is line in file'
      state: present