---
- name: example playbook adding name
  hosts: all
  become: yes
  tasks:
    - name: fist playbook 
      user: name "{{item}}"
      
       with_item:
                - tony
                - jarvis
                
             
                 