---
- name: conditioner example playbook 
  hosts: all
  become: yes
  tasks:
    - name: install a tree package
      apt:
        name: tree
        state: latest
      tags: demo

     - name: install with tree
        apt:
          name
        state: present
      tag: demo 2