---
- name: conditioner example playbook 
  hosts: all
  becomes:
  tasks:
    - name: install a tree pkg
      apt:
        name:tree
        state: latest
      tags: demo
     - name: install with tree
        apt:
        state:
        tag: demo 2