---
- name: install a tree pkg
  hosts: all
  become: yes
  tasks:
    - name: install tree package
      apt:
        name: tree
        state: latest
      tags: 
        - demo

    - name: install with tree
      apt:
        name: tree
        state: present
      tags: 
        - demo 2
